# References
# - https://gist.github.com/dan-blanchard/7045057
# - https://github.com/numba/numba/blob/master/.travis.yml
dist: xenial         # required for Python >= 3.7
language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

branches:
    only:
        - master

before_install:
    # Install Miniconda
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --add channels conda-forge
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda

    # Useful for debugging any issues with conda
    - conda info -a

install:
    # Setup environment
    # - pandas will bring dateutil numpy pytz setuptools six and scipy, we
    #   might want to avoid the later by installing all dependencies manually
    #   except scipy and install pandas with --no-deps
    # - pandas >= 0.20.0 is required since commit 01669f2024a7bffe47cceec0a0fd845f71b6f7cc
    #   (issue 702 : fixed bug when writing metadata using HDF format)
    - conda create -n travisci --yes python=${TRAVIS_PYTHON_VERSION:0:3}
            "numpy>=1.13" "pandas>=0.20" pytables matplotlib openpyxl
            xlsxwriter "pytest>=3.5"
    - source activate travisci
    - pip install pytest-flake8

script:
    - pytest

notifications:
    on_success: "change"
    on_failure: "always"
# use container-based infrastructure
sudo: false
