# References
# - https://gist.github.com/dan-blanchard/7045057
# - https://github.com/numba/numba/blob/master/.travis.yml
language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

# Work-around to enable python 3.7 without globally enabling sudo and dist: xenial for other build jobs
# see https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

branches:
    only:
        - master

before_install:
    # Install Miniconda
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --add channels conda-forge
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda

    # Useful for debugging any issues with conda
    - conda info -a

install:
    # Setup environment
    # pandas will bring dateutil numpy pytz setuptools six and scipy, we
    # might want to avoid the later by installing all dependencies manually
    # except scipy and install pandas with --no-deps
    - conda create -n travisci --yes python=${TRAVIS_PYTHON_VERSION:0:3}
            "numpy>=1.13,!=1.16.*" pandas pytables matplotlib xlrd openpyxl
            xlsxwriter pytest pytest-pep8
    - source activate travisci

script:
    - pytest

notifications:
    on_success: "change"
    on_failure: "always"

# use container-based infrastructure
sudo: false
